vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)

vim.keymap.set("n", "<leader>w", "<cmd>w<cr>")
vim.keymap.set("n", "<leader>q", "<cmd>q<cr>")
vim.keymap.set("n", "<leader>c", "<cmd>bd<cr>")
vim.keymap.set("n", "<leader>R", "<cmd>lua vim.lsp.buf.rename()<cr>")
vim.keymap.set("n", "ac", "<Cmd>noh<CR>")

-- telescope
vim.keymap.set("n", "<leader>ff", function()
	require("telescope.builtin").find_files()
end, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>fw", function()
	require("telescope.builtin").live_grep()
end, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>fb", function()
	require("telescope.builtin").buffers()
end, { desc = "Telescope buffers" })
vim.keymap.set("n", "<leader>fm", function()
	require("telescope.builtin").help_tags()
end, { desc = "Telescope help tags" })
vim.keymap.set("n", "<leader>fm", function()
	require("telescope.builtin").live_grep({ search_dirs = { vim.fn.expand("%:p:h") } })
end, { desc = "Telescope live grep in dir" })
vim.keymap.set("n", "<C-p>", function()
	require("telescope.builtin").git_files()
end, { desc = "Telescope git files" })

vim.keymap.set("n", "<leader>fit", function()
	require("telescope.builtin").live_grep({ glob_pattern = "*.{test,it}*" })
end)
vim.keymap.set("n", "fii", function()
	require("telescope.builtin").live_grep({ glob_pattern = "*.{it}*" })
end)
vim.keymap.set("n", "fif", function()
	require("telescope.builtin").live_grep({ glob_pattern = "!*.{test,it}*" })
end)
vim.keymap.set("n", "fc", function()
	require("telescope.builtin").colorscheme()
end)

-- undotree
vim.keymap.set("n", "<leader>u", vim.cmd.UndotreeToggle)
